var listDangCongSan = 
[
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan", 
        tenHienThi: "Việt Nam ơi mùa xuân đến rồi", 
        tenFile : "DCS01  viet_nam_oi_mua_xuan_den_roi", 
        tacGia : "Thơ: Lê Cảnh – Nhạc: Huy Du", trinhBay : "tốp ca", 
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan", 
        tenHienThi:"Đảng là cuộc sống của tôi", 
        tenFile: "DCS02 dang_la_cuoc_song_cua_toi", 
        tacGia:"Nguyễn Đức Toàn", trinhBay:"Trọng Tấn", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}),
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Bác Hồ một tình yêu bao la", 
        tenFile:"DCS08 Bac Ho mot tinh yeu bao la", 
        tacGia:"Thuận Yến", trinhBay:"Thanh Hoa", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}), 
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Bác đang cùng chúng cháu hành quân", 
        tenFile:"DCS09 Bac dang cung chung chau hanh quan", 
        tacGia:"Huy Thục", trinhBay:"tốp ca",
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}), 
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Đêm nghe hát đò đưa nhớ bác", 
        tenFile:"DCS06 Dem nghe hat do dua nho Bac", 
        tacGia:"An Thuyên", trinhBay:"-", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}),
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Đảng đã cho ta sáng mắt sáng lòng", 
        tenFile:"DCS03 dang_da_cho_ta_sang_mat_sang_long", 
        tacGia:"Phạm Tuyên", trinhBay:"-", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}),
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Đảng ca chào mừng ĐCS Việt Nam", 
        tenFile:"DCS04 dang_ca_chao_mung_dang_cong_san_viet_nam_do_minh", 
        tacGia:"Đỗ Minh", trinhBay:"tốp ca", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}),
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Đảng đã cho ta một mùa xuân", 
        tenFile:"DCS05 dang_da_cho_ta_mot_mua_xuan_ca_si_tran_thuy_mien", 
        tacGia:"Phạm Tuyên", trinhBay:"Trần Thụy Miên", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}),
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Như có Bác Hồ trong ngày vui đại thắng", 
        tenFile:"nhu-co-bac-ho-trong-ngay-vui-dai-thang", 
        tacGia:"Phạm Tuyên", trinhBay:"tốp ca", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"}),
    new BaiHat({rootFolder : rootFolder, folder: "dangCongSan",
        tenHienThi:"Giữa Mạc Tư Khoa nghe câu hò ví dặm", 
        tenFile:"giua-mac-tu-khoa-nghe-cau-ho-vi-dam", 
        tacGia:"Phạm Tuyên", trinhBay:"tốp ca", 
        volume:80, trangThai:-1, 
        autoNext: 1, delayBeforePlay: 0, imageName:"cd"})
];


