var listQueHuongCachMang = 
[
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi: "Vang Mãi khúc quân hành", 
        tenFile: "6 Hat Mai Khuc Quan Hanh - Top Ca [MP3 128kbps]", 
        tacGia: "Diệp Minh Tuyền", trinhBay: "tốp ca", 
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "quyet-thang.png"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi: "BEAT Vang Mãi khúc quân hành", 
        tenFile: "5 Hat mai khuc quan hanh - BEAT", 
        tacGia: "Diệp Minh Tuyền", trinhBay: "tốp ca", 
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "quyet-thang.png"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi: "Chào em cô gái Lam Hồng", 
        tenFile: "ChaoEmCoGaiLamHong-TrungDuc_htu_hq", 
        tacGia: "Ánh Dương", trinhBay: "Trung Đức", 
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi: "Cô gái mở đường", 
        tenFile: "CoGaiMoDuong-CamLy_89r_hq", 
        tacGia: "Xuân Giao", trinhBay: "Cẩm Ly", 
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi: "Đường bốn mùa xuân", 
        tenFile:"Duongbonmuaxuan-TrongTanAnhTho_4794",
        tacGia:"Đỗ Nhuận", trinhBay:"Trọng Tấn - Anh Thơ",
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi:"Qua bến Đò Quan",
        tenFile:"QuaBenDoQuan-TanNhan_jc8_hq",
        tacGia:"Thái Cơ", trinhBay:"Tân Nhàn",
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi:"Tôi người lái xe",
        tenFile:"ToiNguoiLaiXe-V.A-2633684",
        tacGia:"An Chung", trinhBay:"Việt Hoàn",
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi:"Tàu anh qua núi",
        tenFile:"Tau Anh Qua Nui - Anh Tho",
        tacGia:"Phan Lạc Hoa", trinhBay:"Anh Thơ",
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi:"Bài ca Hà Nội",
        tenFile:"Bai Ca Ha Noi",
        tacGia:"Vũ Thanh", trinhBay:"Trọng Tấn",
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"}),	
    new BaiHat({rootFolder: rootFolder, folder: "nhacQueHuongCachMang", 
        tenHienThi:"Hát về cây lúa hôm nay",
        tenFile:"Hat ve cay lua hom nay",
        tacGia:"Hoàng Vân", trinhBay:"Trọng Tấn - Anh Thơ",
        volume: 80, trangThai: -1, 
        autoNext: 1, delayBeforePlay: 0, imageName: "cd"})    
];


